server:
  port: 8090
url: http://m.diyiziti.com/shouxie
canvas:
  width: 720
  height: 1000

spring:
  datasource:
    url: jdbc:mysql://rm-2ze7128ii6i707h5w8o.mysql.rds.aliyuncs.com:3306/javadb?useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC

    username: anjingkun
    password: Ajk@62669002

  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    #  格式化返回时间 yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.qq.com
    username: 853048903@qq.com #自己的邮箱账号
    password: kswtulfynlxbbfhb  #这个不是登录密码而是163授权登录的密码
    default-encoding: UTF-8
  mvc:
    static-path-pattern: /images/**
  resources:
    #static-locations: file:D:/学习资料/安璟坤的项目/手写大师/penalty-writing-terminator/text-generator/src/main/resources/images/
    static-locations: file:/root/images/
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.scj.text.generator.Entity
thymeleaf:
  #prefix: classpath:/templates/  #prefix：指定模板所在的目录
  prefix: /root/templates/
  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
  cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  suffix:  .html
  #encoding: UTF-8
  #content-type: text/html
  mode: HTML5

